version: '3'
services:
  web:
    image: node:14.15.3-alpine
    command: yarn start
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "3000:3000"
  test:
    image: node:14.15.3-alpine
    command: yarn test
    working_dir: /app
    volumes:
      - .:/app
  build:
    image: node:14.15.3-alpine
    command: yarn build
    working_dir: /app
    volumes:
      - .:/app
  json:
    image: node:14.15.3-alpine
    command: yarn server
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "5000:5000"
